pub mod calculation;
mod strafschluck_data;
mod chain_data;
mod drink_avg_data;
mod drink_finished_data;
mod drink_total_data;
mod penalties_data;
mod ppg_data;
mod strafschluck_calc;
mod accuracy_data;
mod ppg_calc;
mod penalties_calc;
mod chain_calc;
mod throw_per_game_data;
mod throw_per_game_calc;
mod drink_calc;
mod side_information_data;
mod side_information_calc;
