pub mod calculation;
pub mod strafschluck_data;
pub mod chain_data;
pub mod drink_avg_data;
pub mod drink_finished_data;
pub mod drink_total_data;
pub mod penalties_data;
pub mod ppg_data;
pub mod strafschluck_calc;
pub mod accuracy_data;
pub mod ppg_calc;
pub mod penalties_calc;
pub mod chain_calc;
pub mod throw_per_game_data;
pub mod throw_per_game_calc;
pub mod drink_calc;
pub mod side_information_data;
pub mod side_information_calc;
mod running_calc;
mod running_data;
